### ISSUE TITLE
boTTT issue

### ISSUE THREAD

**Issue by CharlesCarmichael** [TalkTakesTime/Pokemon-Showdown-Bot#41]
Had an issue where using the .vab command made boTTT disconnect from the server entirely. http://prntscr.com/640qeq here is a screenshot of it. I had checked in multiple rooms, and boTTT had left all of them. I tried .vab in both THP and in Studio, both wielded the same results.

**Comment by Morfent** [comment]
That sounds like a bug with .vab. boTTT's not disconnecting; it's crasihng. I'll take a look into it.

**Comment by Morfent** [comment]
I could not get this to trigger in either of the rooms you mentioned.

**Comment by Freigeist** [comment]
It was more like a temporary issue, but it only affected .vab not .vbw which was a very weird behaviour

**Comment by Morfent** [comment]
Forgot about this issue. The bot would crash if it could not connect to Hastebin, which I'm guessing is what was happening here. This was solved in ea2bece4a56139b18ae19f6e7943669ebd4de0b1
