### ISSUE TITLE
Why are we using vinilla node instead of better alternatives?

### ISSUE THREAD

**Issue by panpawn** [TalkTakesTime/Pokemon-Showdown-Bot#42]
As stated in the title, vanilla node is limiting when it comes to running any reliable script.  If that script crashes (as shown in the previous "issue") then a lot of people will have to wait for someone to go into the VPS to restart it.

However, if a better alternative such as forever is used, then it will restart the script if it were to crash.  This would then make the bot a lot more reliable in terms of up-time as well.

**Comment by TalkTakesTime** [comment]
I don't know about Morfent, but when I ran my bot I always used forever. However, I don't think this is necessarily something that you should force a user into doing; I prefer just leaving it as it is and leaving it up to the user to run it as they wish.

**Comment by Morfent** [comment]
I do use forever.

**Comment by Morfent** [comment]
So what exactly are you tryiing to ask for, @panpawn? Forcing people to use forever to run the bot is not reasonable, in my opinion.

**Comment by panpawn** [comment]
I was mainly asking if the boTTT on main was using forever and if not why not.

Thanks for the clarification.
