### ISSUE TITLE
Babel is outdated

### ISSUE THREAD

**Issue by Joimer** [TalkTakesTime/Pokemon-Showdown-Bot#67]
juanma@le-toucan:/home/proyectos/Pokemon-Showdown-Bot$ npm install
npm WARN deprecated babel-core@5.8.24: Babel 5 is no longer being maintained. Upgrade to Babel 6.

**Comment by TalkTakesTime** [comment]
This project was officially abandoned 6 months ago and is no longer maintained, as noted in the [README](https://github.com/TalkTakesTime/Pokemon-Showdown-Bot/blob/master/README.md). Feel free to fork it and fix the issue on your fork, but issues or pull requests are no longer dealt with or accepted.
